name: Selenium Ide CI

on:
  push:
      branches:
         - main
  pull_request:
      branches:
         - main  
jobs:
    build:
        runs-on: ubuntu-lates

    steps:
    - name: Checkout code
      uses: actions/checout@v3
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' 
        
    - name: Install dependencies
      run: dotnet restore    
      
    - name: Build
      run: dotnet build --no-restore 
      
    - name: Run tests
      run: dotnet tests --verbosity normal    